language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "pypy"
install:
    - "pip install -r requirements.txt"
    - "pip install flake8 ipython"
script:
    - "make test"
notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.org#noswap"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
        use_notice: true
        skip_join: true
